#!/bin/bash

work_time=60*25
break_time=60*5

function notify {
  terminal-notifier -title Pomodoro -sound Ping -message "${*:1}"
}

function work {
  notify "get to work!"
  sleep $work_time && rest
}

function rest {
  notify "time for a break!"
  sleep $break_time && work
}

case "$1" in
  work)
    work
  ;;
  rest)
    rest
  ;;
esac
