#!/bin/bash

work_time=1500
break_time=300

function notify {
  terminal-notifier -title Pomodoro -sound Ping -message "${*:1}"
}

function work {
  notify "WERKZEIT"
  sleep $work_time && rest
}

function rest {
  notify "SCHLAFZEIT"
  sleep $break_time && work
}

case "$1" in
  work)
    work
  ;;
  rest)
    rest
  ;;
esac
